# Generated by Django 3.0.6 on 2020-08-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studentinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('father_n', models.CharField(max_length=50)),
                ('mother_n', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('course', models.CharField(max_length=50)),
            ],
        ),
    ]
