# Generated by Django 3.0.6 on 2020-09-05 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_studentmarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentmarks',
            new_name='Studentmark',
        ),
    ]
